dist: xenial

language: php

php:
  - '7.2'

addons:
  mariadb: 10.4

cache:
  yarn: true
  directories:
    - node_modules
    - vendor

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq nodejs yarn
  - sudo mysql -e 'CREATE DATABASE apitestdb;'
  - composer self-update

install:
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  - yarn install --ignore-optional --non-interactive
  - npm run production
  - php artisan --env=testing migrate:refresh --force
  - php artisan --env=testing swagger-lume:generate
  - php -S localhost:8000 -t public &

script:
  - php vendor/bin/phpunit -v --coverage-text --colors=never --stderr
